
--Phase 4: GROUP BY Business Questions
--31.Top 10 states by number of customers.
SELECT customer_state, COUNT(*) AS top_customers
FROM customers
GROUP BY customer_state
ORDER BY top_customers desc
LIMIT 10;

--32.Top 10 cities by customers.
SELECT customer_city, COUNT(*) AS top_customers
FROM customers
GROUP BY customer_city
ORDER BY top_customers DESC
LIMIT 10;

--33.Top payment methods by usage.
SELECT payment_type ,COUNT(*) AS payment_method
FROM order_payments
GROUP BY payment_type
ORDER BY payment_method DESC
LIMIT 1;

--34.Product categories with the highest number of products.
SELECT product_category_name ,COUNT(*)as number_of_products
FROM products
GROUP BY product_category_name
ORDER BY  number_of_products DESC
LIMIT 3;

--35.States with the most sellers.
SELECT seller_state ,COUNT(*)as number_of_sellers
FROM sellers
GROUP BY seller_state
ORDER BY number_of_sellers DESC
LIMIT 3;

--36.Average review score by order status.
select 
o.order_status,
AVG(r.review_score) AS  avg_review_score
FROM orders o
join order_reviews r
on o.order_id=r.order_id
group by order_status
order by avg_review_score  desc;

--37.Revenue generated by each payment type.
select payment_type,SUM(payment_value) as total_revnue
from order_payments
group by payment_type
order by total_revnue desc;

--38.Average freight cost by seller state.
select 
s.seller_state,AVG(oi.freight_value) as avg_freight_cost
FROM sellers s
join order_item oi
on s.seller_id=oi.seller_id
group by seller_state
order by avg_freight_cost desc;

--39.Orders count by month.
select 
extract(month from order_purchase_timestamp) as month,
count(order_id) as total_orders
from orders
group by month
order by month;
-- or 
SELECT
    DATE_TRUNC('month', order_purchase_timestamp) AS month,
    COUNT(*) AS total_orders
FROM orders
GROUP BY month
ORDER BY month desc;

--40.Revenue generated by year.
SELECT
    DATE_TRUNC('year', o.order_purchase_timestamp) AS year,
    SUM(op.payment_value) AS total_revenue
FROM orders o
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY year
ORDER BY year;
